services:
  # ===============================
  # 🧠 SERVICE 1: Flask API
  # ===============================
  - type: web
    name: ipa-api              # 👈 bạn có thể giữ nguyên hoặc đổi tên
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_BRANCH
        sync: false

  # ===============================
  # 🤖 SERVICE 2: Telegram Bot
  # ===============================
  - type: worker
    name: ipa-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
      - key: GITHUB_BRANCH
        sync: false
