services:
  - type: web
    name: ipa-bot-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_REPO
        sync: false
